version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: studypal
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always

  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 studypal.asgi:application
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/studypal
      - REDIS_URL=redis://redis:6379
    ports:
      - "8000:8000"

  worker:
    build: .
    command: celery -A studypal worker --loglevel=info
    depends_on:
      - redis
      - db
      - web
    environment:
      - REDIS_URL=redis://redis:6379

  beat:
    build: .
    command: celery -A studypal beat --loglevel=info
    depends_on:
      - worker
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

volumes:
  postgres_data:
