# Generated by Django 5.1.7 on 2025-03-15 16:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('achievement_type', models.CharField(choices=[('streak', 'Streak Milestone'), ('quiz', 'Quiz Performance'), ('course', 'Course Completion'), ('engagement', 'Platform Engagement')], max_length=20)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='achievement_icons/')),
                ('awarded_on', models.DateTimeField(auto_now_add=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Achievements',
                'ordering': ['-awarded_on'],
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='badges/')),
                ('awarded_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Badges',
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Leaderboards',
                'ordering': ['-total_xp'],
            },
        ),
        migrations.CreateModel(
            name='StudyStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('longest_streak', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_study_date', models.DateField(blank=True, null=True)),
                ('total_study_days', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Study Streaks',
                'ordering': ['-current_streak'],
            },
        ),
        migrations.CreateModel(
            name='XPSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'XP System',
                'verbose_name_plural': 'XP Systems',
            },
        ),
    ]
