# Generated by Django 5.1.7 on 2025-03-20 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('web_notifications', models.BooleanField(default=True)),
                ('achievement_notifications', models.BooleanField(default=True)),
                ('streak_notifications', models.BooleanField(default=True)),
                ('study_reminder_notifications', models.BooleanField(default=True)),
                ('exam_reminder_notifications', models.BooleanField(default=True)),
                ('course_update_notifications', models.BooleanField(default=True)),
                ('quiz_result_notifications', models.BooleanField(default=True)),
                ('ai_insight_notifications', models.BooleanField(default=True)),
                ('daily_notification_limit', models.IntegerField(default=10)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('achievement', 'Achievement'), ('streak', 'Streak'), ('study_reminder', 'Study Reminder'), ('exam_reminder', 'Exam Reminder'), ('course_update', 'Course Update'), ('quiz_result', 'Quiz Result'), ('ai_insight', 'AI Insight'), ('system', 'System')], default='system', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('source_model', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_enhanced', models.BooleanField(default=False)),
                ('ai_insights', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='notificatio_user_id_e89e13_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
    ]
