name: Deploy to Server

on:
  push:
    branches:
      - main  # Change this if your main branch is named differently

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/studypal:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/studypal:latest

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/studypal:latest
            docker stop studypal || true
            docker rm studypal || true
            docker run -d --name studypal -p 80:80 \
              --env-file /home/${{ secrets.SERVER_USER }}/.env \
              ${{ secrets.DOCKER_HUB_USERNAME }}/studypal:latest
